IEP-203 Can't delete a Launch Target
espressif/idf-eclipse-plugin pull request #235
Opened 2021-04-01 08:17 UTC by sigmaaa

Added option to delete a launch target:
![IEP-203](https://user-images.githubusercontent.com/24419842/113264100-de949900-92d2-11eb-8b8a-fdc8580744b7.png)

after deleting, a launch target is still in the launch bar until the eclipse is not restarted. To inform the user about it, the information dialog was added: 

![IEP-203 info dial](https://user-images.githubusercontent.com/24419842/113264115-e18f8980-92d2-11eb-9620-5c6b70874758.png)

I

2021-04-05 06:27 UTC, kolipakakondal requested changes
Hi @sigmaaa 

From the user's experience perspective, this behavior is not accepted. We can check how we can refresh the deleted items

2021-04-12 07:52 UTC, kolipakakondal commented
Hi @sigmaaa 

The below approach seems to work. Please change accordingly and update the PR

```
@Override
	public void performDelete() {
		ILaunchTargetManager targetMgr = Activator.getService(ILaunchTargetManager.class);
		ILaunchTarget target = getLaunchTarget();
		if (target != null) {
			targetMgr.removeLaunchTarget(target);
		}
	}
```

2021-04-12 08:42 UTC, kolipakakondal approved these changes
LGTM

2021-04-12 08:42 UTC, merged

2021-04-12 08:43 UTC, sigmaaa commented
> Hi @sigmaaa
> 
> The below approach seems to work. Please change accordingly and update the PR
> 
> ```
> @Override
> 	public void performDelete() {
> 		ILaunchTargetManager targetMgr = Activator.getService(ILaunchTargetManager.class);
> 		ILaunchTarget target = getLaunchTarget();
> 		if (target != null) {
> 			targetMgr.removeLaunchTarget(target);
> 		}
> 	}
> ```

Hi @kolipakakondal

PR is updated. Thanks for help!