IEP-446: IDF Components Install Page and Manager (Updated Branch & PR)
espressif/idf-eclipse-plugin pull request #407
Opened 2021-11-19 12:28 UTC by alirana01

2021-12-02 16:32 UTC, sigmaaa requested changes
Looks like

> add-dependency

command was added in the ESP-IDF 4.4 (I can't use install button on 4.3). We can mention this in documentation. 
Also, I'm getting an error, when i'm trying to install components with more then one symbol "_"or "-" at the component's name. For example on 

> diamond_dependecy_c:

```
Executing action: add-dependency
Invalid dependency version requirement: _c>=1. Please use format like ">=1" or "*". 
```

2021-12-02 16:32 UTC, sigmaaa commented on bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/installcomponents/handler/InstallCommandHandler.java
> +		commands.add(namespace.concat("/").concat(name.concat("==").concat(version))); //$NON-NLS-1$ //$NON-NLS-2$
what if the component's version is not specified?

2021-12-13 09:37 UTC, kolipakakondal commented
Hi @alirana01  @sigmaaa  Can we merge this?

2021-12-15 09:38 UTC, merged

2021-12-15 09:38 UTC, alirana01 commented
@kolipakakondal merged into master