IEP-525 Show Application RAM and flash usage info after the build
espressif/idf-eclipse-plugin pull request #430
Opened 2022-01-05 19:35 UTC by sigmaaa

Now, after the build, we can see the application's RAM and flash usage using the idf_size.py command:

<img width="622" alt="Screenshot 2022-01-05 at 20 56 50" src="https://user-images.githubusercontent.com/24419842/148277347-86d4bb6e-5841-4170-bd65-fb48ca88f90d.png">

If the remaining app size is less than 30%, we will show the warning message with the link to the [documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html?highlight=partitions%20csv#creating-custom-tables)

<img width="654" alt="Screenshot 2022-01-05 at 20 56 20" src="https://user-images.githubusercontent.com/24419842/148277774-26020dd3-fd0a-47a5-8bc0-4f46105a9e47.png">

2022-01-05 21:22 UTC, sigmaaa commented
Hi @igrr, good point. I'll add that. Thanks!

2022-01-05 22:27 UTC, sigmaaa commented
Hi, @igrr. After the latest commit, the message dialog looks like this:
<img width="655" alt="Screenshot 2022-01-06 at 0 09 39" src="https://user-images.githubusercontent.com/24419842/148298404-bf972950-e7a2-4b95-a104-35fbd079b9db.png">

2022-01-06 08:18 UTC, kolipakakondal requested changes
Thanks @sigmaaa for the PR. LGTM. A couple of other things we could consider - 

- Refactor code -  Move all partition size checking code into the `ParitionSizeHandler` class and invoke it from the IDFBuildConfiguration. This includes checkRemainingSize, getPartitionTable, startIdfSizeProcess and getMapFilePath() etc.
- When we are showing a warning message to the user, maybe we could be very specific on the size details. 

For example, I could suggest something like this `Less than 30% of application partition size is free(X of Y MB), would you like to increase it? Please click here to check more details.`

2022-01-06 14:45 UTC, sigmaaa commented on bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/MessageLinkDialog.java
> +		if (!preferences.getBoolean(DO_NOT_SHOW_MSG, false))
Thanks, @kolipakakondal for the review, added the requested changes. Now message looks like this:
<img width="655" alt="Screenshot 2022-01-06 at 16 33 09" src="https://user-images.githubusercontent.com/24419842/148400357-31578e63-a94c-4965-be88-a5ffe56e8f7d.png">

2022-01-06 14:45 UTC, sigmaaa commented on bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/messages.properties
> +IncreasePartitionSizeMessage=Consider increasing the application partition size, see <a href=\"https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html?highlight=p
done

2022-01-06 14:45 UTC, sigmaaa commented on bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/MessageLinkDialog.java
> +public class MessageLinkDialog extends MessageDialog
done

2022-01-07 08:42 UTC, kolipakakondal approved these changes
LGTM

2022-01-07 13:46 UTC, merged