Iep 552
espressif/idf-eclipse-plugin pull request #454
Opened 2022-01-27 08:44 UTC by alirana01

Added a preferences page to set the timeout also updated the default timeout with 25 seconds from 15 seconds

2022-01-27 09:10 UTC, kolipakakondal commented
Hi @alirana01  Could you add this directly under espressif main page as we have just one property to configure? In fact, we could also move the serial monitor settings configuration to the main page. We could use groups wherever we have multiple settings to configure.


<img width="1086" alt="Screenshot 2022-01-27 at 2 37 58 PM" src="https://user-images.githubusercontent.com/8463287/151327291-ad4fdcc2-e02e-40c1-9879-c33c02cfe181.png">

2022-01-31 07:28 UTC, alirana01 commented
> Hi @alirana01 Could you add this directly under espressif main page as we have just one property to configure? In fact, we could also move the serial monitor settings configuration to the main page. We could use groups wherever we have multiple settings to configure.
> 
> <img alt="Screenshot 2022-01-27 at 2 37 58 PM" width="1086" src="https://user-images.githubusercontent.com/8463287/151327291-ad4fdcc2-e02e-40c1-9879-c33c02cfe181.png">

Hi @kolipakakondal the requested changes are made, please review the PR.

Thanks

2022-02-03 06:02 UTC, kolipakakondal requested changes

2022-02-03 06:02 UTC, kolipakakondal commented
<img width="640" alt="Screenshot 2022-02-03 at 11 30 50 AM" src="https://user-images.githubusercontent.com/8463287/152289701-1a4ddefe-64d1-4f9e-a234-21a629961e60.png">

Please find the reference

2022-02-03 09:12 UTC, alirana01 commented on bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/preferences/messages.properties
> +GDBServerTimeoutPage_TimeoutField=Timeout for gdb server launch timeout
Done

2022-02-03 09:12 UTC, alirana01 commented on bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/preferences/EspresssifPreferencesPage.java
> +		addField(numberOfLines);
Done
<img width="325" alt="image" src="https://user-images.githubusercontent.com/85216275/152313365-d1a940de-ed87-4e53-a0cd-8e8eb90d84a3.png">

2022-02-03 16:54 UTC, kolipakakondal commented on bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/preferences/EspresssifPreferencesPage.java
> +		addField(numberOfLines);
@alirana01 Please keep grouping only if you have more than one property/field, otherwise, it looks good we could merge the PR

2022-02-08 07:28 UTC, merged