IEP-787: Replace the CMake change with a project description reader to find project binaries.
espressif/idf-eclipse-plugin pull request #615
Opened 2022-10-25 09:52 UTC by sigmaaa

## Description

For now, we are changing the CMake file after project creation, so project binaries will always have the same name as the project, but with this approach, some templates don't work. 

This PR contains a refactoring of the places where we look for binaries and a replacement based on calling the project name with the value from project_decsription.json. 
As example:
```
elfFilePath = project.getProject().getFolder("build").getFile(project.getName().replace(" ", "_").concat(".elf")).getLocation() 
.toString();

```
replaced with:

```
IFile elfFile = new ProjectDescriptionReader(project.getProject()).getAppElfFile();
elfFilePath = elfFile == null ? null : elfFile.getLocation().toString();
```

Fixes # ([IEP-787](https://jira.espressif.com:8443/browse/IEP-787))

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## How has this been tested?

So far I have found only two places where these changes have had an impact. Application Level Tracing and Heap Tracing, so tests were next:

- Test application level tracing feature with different project names
- Test heap tracing feature with different project names

**Test Configuration**:
* ESP-IDF Version:
* OS (Windows,Linux and macOS):

## Dependent components impacted by this PR:

- Application Level Tracing
- Heap Tracing
- some other places, where we are looking for binaries?

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

2022-11-30 13:51 UTC, kolipakakondal requested changes
LGTM.

2022-11-30 13:51 UTC, kolipakakondal commented on bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/ProjectDescriptionReader.java
> +		try (FileReader reader = new FileReader(projectDescriptionJsonFile))
Can we use GenericJsonReader to read this as we already using this here https://github.com/espressif/idf-eclipse-plugin/blob/f0304d96aa3692b784b088aefbd22fd4bb4effcd/bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/IDFUtil.java#L531

2022-12-08 11:56 UTC, kolipakakondal commented
Hi @AndriiFilippov could you please check this

2022-12-13 08:50 UTC, AndriiFilippov commented
Hi @sigmaaa ! 

Tested under: 
OS: Windows 10
ESP-IDF: v5.0/master 

LGTM. 👍

2022-12-13 10:33 UTC, merged