IEP-952: Espressif IDE popup for old tool versions popping up after installing tools via IDE
espressif/idf-eclipse-plugin pull request #770
Opened 2023-05-25 15:17 UTC by alirana01

## Description

Checking the esp_idf.json timestamp for env initialization

Fixes # ([IEP-952](https://jira.espressif.com:8443/browse/IEP-952))

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## How has this been tested?

Use the tests in the following PR (https://github.com/espressif/idf-eclipse-plugin/pull/662). 
Also try to install the tools in the IDE after the IDE is initialized via esp_idf.json file and try to close and reopen the IDE to see if the message popup appears. The original jira ticket also contains links to the forum and github issues.

**Test Configuration**:
* ESP-IDF Version: Any
* OS (Windows,Linux and macOS): Windows only (Since installer is currently given for Windows only)

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting

2023-05-26 04:58 UTC, kolipakakondal requested changes
LGTM. But this breaks the backward compatability as every user will be prompted with message dialog on IDE restart for the first time (lastmodified > -1)

Can we do something about it?

2023-05-26 04:58 UTC, kolipakakondal commented on bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java
> +	private static final String LAST_MODIFIED_ESP_IDF_JSON_FILE = "lastModifed-esp_idf.json"; //$NON-NLS-1$
Name is bit misleading, my initial impression was you're trying to store lastmodified timestamp in the `lastModifed-esp_idf.json` file. How about something like this  `esp_idf_json_lastmodified_timestamp` or similar?

2023-05-26 08:13 UTC, sigmaaa commented on bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java
> +		else if (isConfigFileUpdated(idf_json_file))
Hi @alirana01, what will happen, if idf_json_file is modified and we click `NO`? It looks like if we store preferences like that: 
`prefs.putLong(LAST_MODIFIED_ESP_IDF_JSON_FILE, idf_json_file.lastModified());` then this condition returns false after second eclipse restart and we will update our environment with new idf_json_file anyway `updateEnvUsingIdfJsonFile(idf_json_file);`. It's not clear to me, to be honest, can you explain?

2023-05-26 08:13 UTC, sigmaaa commented on bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java
> +		updateEnvUsingIdfJsonFile(idf_json_file);
even if we click No, we will get here after the second eclipse restart, am I missing something here?

2023-05-26 08:17 UTC, sigmaaa reviewed
Hi @alirana01, some moments are not clear to me, can you explain, please?

2023-05-26 08:35 UTC, alirana01 commented
I have added the required changes @kolipakakondal @sigmaaa kindly review again

2023-05-30 07:38 UTC, sigmaaa approved these changes
LGTM

2023-06-01 11:41 UTC, kolipakakondal approved these changes
LGTM

2023-06-05 09:17 UTC, AndriiFilippov commented
@alirana01 hi ! 

Tested: 
OS - Windows 10 
ESP-IDF: v4.4 / v5.2 

Install tools v4.4 via Windows Tools Installer -> switch to ESP-IDF v5.2 -> able to see popup window -> "Yes" -> it change the idf path under  esp_idf.json file -> "No" -> update esp_idf.json. 

Do not see popup window again after re-open project.

LGTM 👍

2023-06-06 03:31 UTC, merged